[package]
name = "gitlab-merge-requests"
version = "0.1.0"
authors = ["Romain Baumier <baumier.romain@gmail.com>"]
edition = "2018"

[dependencies]
alfred = "4.0.1"
reqwest = "0.9.18"
serde = "1.0.92"
chrono = { version = "0.4.10", features = ["serde"] }
